CREATE TABLE [dbo].[AUDIT] (
    [ACTION_TYPE] NCHAR (1)      NULL,
    [TABLE_NAME]  NVARCHAR (255) NULL,
    [PK_VALUE]    NVARCHAR (255) NULL,
    [COLUMN_NAME] NVARCHAR (255) NULL,
    [OLD_VALUE]   NVARCHAR (255) NULL,
    [NEW_VALUE]   NVARCHAR (255) NULL,
    [LOG_TIME]    SMALLDATETIME  NULL,
    [LOG_USER]    VARCHAR (128)  NULL,
    [ROW_ID]      BIGINT         IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_AUDIT] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

