CREATE TABLE [dbo].[DIM_CURRENCY] (
    [CURRENCY_ID]   INT            IDENTITY (1, 1) NOT NULL,
    [DIGITAL_CODE]  INT            NULL,
    [CURRENCY_CODE] NVARCHAR (3)   NULL,
    [CURRENCY_NAME] NVARCHAR (255) NULL,
    [LOAD_TIME]     SMALLDATETIME  CONSTRAINT [DF_DIM_CURRENCY_LOAD_TIME] DEFAULT (getdate()) NULL,
    [LOAD_DATE]     AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);

