CREATE TABLE [dbo].[DIM_AIRPORT] (
    [AIRPORT_CODE]      NVARCHAR (255) NULL,
    [AIRPORT_DESC]      NVARCHAR (255) NULL,
    [LATITUDE]          NVARCHAR (255) NULL,
    [LONGITUDE]         NVARCHAR (255) NULL,
    [CITY_CODE]         NVARCHAR (255) NULL,
    [CITY_DESC]         NVARCHAR (255) NULL,
    [COUNTRY_CODE]      NVARCHAR (255) NULL,
    [COUNTRY_DESC]      NVARCHAR (255) NULL,
    [COUNTRYGROUP_CODE] NVARCHAR (255) NULL,
    [COUNTRYGROUP_DESC] NVARCHAR (255) NULL,
    [SUBREGION_CODE]    NVARCHAR (255) NULL,
    [SUBREGION_DESC]    NVARCHAR (255) NULL,
    [REGION_CODE]       NVARCHAR (255) NULL,
    [REGION_DESC]       NVARCHAR (255) NULL,
    [AREA_CODE]         NVARCHAR (255) NULL,
    [AREA_DESC]         NVARCHAR (255) NULL,
    [LOAD_TIME]         SMALLDATETIME  CONSTRAINT [DF_DIM_AIRPORT_LOAD_TIME] DEFAULT (getdate()) NULL,
    [LOAD_DATE]         AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);


GO
CREATE NONCLUSTERED INDEX [IX_DIM_AIRPORT_AIRPORT_CODE]
    ON [dbo].[DIM_AIRPORT]([AIRPORT_CODE] ASC)
    INCLUDE([LATITUDE], [LONGITUDE]);

