CREATE TABLE [dbo].[DIM_FLEET] (
    [TRANSPORT_CODE]      NVARCHAR (255) NULL,
    [TRANSPORTATION_TYPE] NVARCHAR (255) NULL,
    [MANUFACTURER]        NVARCHAR (255) NULL,
    [PASSENGER_OR_CARGO]  NVARCHAR (255) NULL,
    [LEASING_TYPE]        NVARCHAR (255) NULL,
    [SEATS_REGULAR]       INT            NULL,
    [SEATS_CHARTER]       INT            NULL,
    [LOAD_TIME]           SMALLDATETIME  NULL,
    [LOAD_DATE]           AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);

