CREATE TABLE [dbo].[DIM_DD_PERIOD] (
    [DATE_KEY]                    INT          NOT NULL,
    [DATE_VALUE]                  DATE         NULL,
    [DATE_STRING]                 CHAR (10)    NULL,
    [DAY_OF_MONTH]                INT          NULL,
    [DAY_SUFFIX]                  VARCHAR (4)  NULL,
    [DAY_NAME]                    VARCHAR (9)  NULL,
    [DAY_OF_WEEK]                 INT          NULL,
    [DAY_OF_WEEK_IN_MONTH]        INT          NULL,
    [DAY_OF_WEEK_IN_YEAR]         INT          NULL,
    [DAY_OF_QUARTER]              INT          NULL,
    [DAY_OF_YEAR]                 INT          NULL,
    [WEEK_OF_MONTH]               INT          NULL,
    [WEEK_OF_QUARTER]             INT          NULL,
    [WEEK_OF_YEAR]                INT          NULL,
    [MONTH_NUM]                   INT          NULL,
    [MONTH_NAME]                  VARCHAR (9)  NULL,
    [MONTH_OF_QUARTER]            INT          NULL,
    [QUARTER_NUM]                 INT          NULL,
    [QUARTER_NAME]                VARCHAR (9)  NULL,
    [YEAR_NUM]                    INT          NULL,
    [YEAR_NAME]                   CHAR (7)     NULL,
    [MONTH_YEAR]                  CHAR (10)    NULL,
    [YYYYMM]                      INT          NULL,
    [FIRST_DAY_OF_MONTH]          DATE         NULL,
    [LAST_DAY_OF_MONTH]           DATE         NULL,
    [FIRST_DAY_OF_QUARTER]        DATE         NULL,
    [LAST_DAY_OF_QUARTER]         DATE         NULL,
    [FIRST_DAY_OF_YEAR]           DATE         NULL,
    [LAST_DAY_OF_YEAR]            DATE         NULL,
    [IS_HOLIDAY]                  BIT          NULL,
    [IS_WEEKEND]                  BIT          NULL,
    [HOLIDAY_NAME]                VARCHAR (50) NULL,
    [FISCAL_DAY_OF_YEAR]          VARCHAR (3)  NULL,
    [FISCAL_WEEK_OF_YEAR]         VARCHAR (3)  NULL,
    [FISCAL_MONTH_NUM]            VARCHAR (2)  NULL,
    [FISCAL_QUARTER_NUM]          CHAR (1)     NULL,
    [FISCAL_QUARTER_NAME]         VARCHAR (9)  NULL,
    [FISCAL_YEAR_NUM]             CHAR (4)     NULL,
    [FISCAL_YEAR_NAME]            CHAR (7)     NULL,
    [FISCAL_MONTH_YEAR]           CHAR (10)    NULL,
    [FISCAL_YYYYMM]               CHAR (6)     NULL,
    [FISCAL_FIRST_DAY_OF_MONTH]   DATE         NULL,
    [FISCAL_LAST_DAY_OF_MONTH]    DATE         NULL,
    [FISCAL_FIRST_DAY_OF_QUARTER] DATE         NULL,
    [FISCAL_LAST_DAY_OF_QUARTER]  DATE         NULL,
    [FISCAL_FIRST_DAY_OF_YEAR]    DATE         NULL,
    [FISCAL_LAST_DAY_OF_YEAR]     DATE         NULL,
    PRIMARY KEY CLUSTERED ([DATE_KEY] ASC)
);

