CREATE TABLE [dbo].[LOG_CFO] (
    [PNL_ITEM]  NVARCHAR (255) NULL,
    [CFO_NAME]  NVARCHAR (255) NULL,
    [MONTH_ID]  INT            NULL,
    [VERSION]   NVARCHAR (255) NULL,
    [LAYER_ID]  AS             ((0)) PERSISTED NOT NULL,
    [FLD_NAME]  AS             (N'PNL_AMOUNT') PERSISTED NOT NULL,
    [OLD_VALUE] FLOAT (53)     NULL,
    [NEW_VALUE] FLOAT (53)     NULL,
    [LOG_TIME]  SMALLDATETIME  NULL,
    [LOG_USER]  NVARCHAR (255) NULL
);

