CREATE TABLE [dbo].[LOG_ERROR] (
    [ROW_ID]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [ERR_DESC]      NVARCHAR (1000) NOT NULL,
    [SOURCE_OBJECT] NVARCHAR (255)  NULL,
    [SOURCE_USER]   NVARCHAR (255)  NULL,
    [LOG_TIME]      DATETIME        CONSTRAINT [DF_ERROR_LOG_DATE_LOAD] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_LOG_ERROR] PRIMARY KEY CLUSTERED ([ROW_ID] ASC)
);

