CREATE TABLE [dbo].[LOG_PROFIT_LOSS] (
    [PNL_ITEM]  NVARCHAR (255) NULL,
    [FLIGHT]    NVARCHAR (255) NULL,
    [MONTH_ID]  INT            NULL,
    [VERSION]   NVARCHAR (255) NULL,
    [FLD_NAME]  AS             (N'PNL_AMOUNT') PERSISTED NOT NULL,
    [OLD_VALUE] FLOAT (53)     NULL,
    [NEW_VALUE] FLOAT (53)     NULL,
    [LOG_TIME]  SMALLDATETIME  NULL,
    [LOG_USER]  NVARCHAR (255) NULL
);

