CREATE TABLE [dbo].[PBL_CFO] (
    [VERSION]    NVARCHAR (255) NULL,
    [LAYER_ID]   NVARCHAR (255) NULL,
    [ITEM]       NVARCHAR (255) NULL,
    [CFO_NAME]   NVARCHAR (255) NULL,
    [MONTH_ID]   NVARCHAR (255) NULL,
    [CFO_AMOUNT] FLOAT (53)     NULL,
    [LOAD_TIME]  DATETIME       CONSTRAINT [DF_PBL_CFO_LOAD_DATE] DEFAULT (getdate()) NULL,
    [LOAD_DATE]  AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);

