CREATE TABLE [dbo].[PBL_PROFIT_LOSS] (
    [VERSION]    NVARCHAR (255) NULL,
    [LAYER_ID]   NVARCHAR (255) NULL,
    [ITEM]       NVARCHAR (255) NULL,
    [MONTH_ID]   NVARCHAR (255) NULL,
    [FLT_DESC]   NVARCHAR (255) NULL,
    [PNL_AMOUNT] FLOAT (53)     NULL,
    [LOAD_TIME]  DATETIME       CONSTRAINT [DF_PBL_PROFIT_LOSS_LOAD_TIME] DEFAULT (getdate()) NULL,
    [LOAD_DATE]  AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);

