CREATE TABLE [dbo].[PBL_SCHEDULE_FLIGHT_TIME] (
    [LAYER_ID]        NVARCHAR (255) NULL,
    [VERSION]         NVARCHAR (255) NULL,
    [FLT_DESC]        NVARCHAR (255) NULL,
    [DATE]            NVARCHAR (255) NULL,
    [RNG_ID]          NVARCHAR (255) NULL,
    [FLIGHT_TIME_DEP] FLOAT (53)     NULL,
    [FLIGHT_TIME_ARR] FLOAT (53)     NULL,
    [HUB_TIME_DEP]    FLOAT (53)     NULL,
    [HUB_TIME_ARR]    FLOAT (53)     NULL,
    [LOAD_TIME]       DATETIME       CONSTRAINT [DF_PBL_SCHEDULE_FLIGHT_TIME_LOAD_DATE] DEFAULT (getdate()) NULL,
    [LOAD_DATE]       AS             (CONVERT([date],[LOAD_TIME])) PERSISTED
);

