CREATE TABLE [dbo].[WRB_PROFIT_LOSS] (
    [PNL_AMOUNT_0]    FLOAT (53)     NULL,
    [MONTH_ID_1]      INT            NULL,
    [ITEM_2]          NVARCHAR (255) NULL,
    [VERSION_3]       NVARCHAR (255) NULL,
    [FLT_DESC_4]      NVARCHAR (255) NULL,
    [MS_AUDIT_TIME_5] DATETIME       NULL,
    [MS_AUDIT_USER_6] NVARCHAR (255) NULL
);


GO

CREATE TRIGGER [dbo].[TR_WRB_PROFIT_LOSS_AFTER_INSERT] ON [dbo].[WRB_PROFIT_LOSS]
AFTER INSERT NOT FOR REPLICATION 
AS
 BEGIN
	EXEC [dbo].[P_UPDATE_FCT_PROFIT_LOSS] ;
END

