{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ ;DWH_VC_AVT",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": ".",
            "database": "DWH_VC_AVT"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "ServiceAccount",
          "EncryptConnection": false
        }
      }
    ],
    "tables": [
      {
        "name": "VERSION",
        "columns": [
          {
            "name": "VERSION",
            "dataType": "string",
            "sourceColumn": "VERSION"
          },
          {
            "name": "VERSION_TYPE",
            "dataType": "string",
            "sourceColumn": "VERSION_TYPE"
          },
          {
            "name": "FORMULA",
            "dataType": "string",
            "sourceColumn": "FORMULA"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_DIM_VERSION = Source{[Schema=\"dbo\",Item=\"V_DIM_VERSION\"]}[Data]",
                "in",
                "    dbo_V_DIM_VERSION"
              ]
            }
          }
        ]
      },
      {
        "name": "CFO",
        "columns": [
          {
            "name": "CFO_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CFO_ID",
            "displayFolder": "HIDDEN"
          },
          {
            "name": "CFO_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CFO_NAME",
            "displayFolder": "HIDDEN"
          },
          {
            "name": "CFO_PARENT_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CFO_PARENT_NAME",
            "displayFolder": "HIDDEN"
          },
          {
            "name": "CFO_TYPE",
            "dataType": "string",
            "sourceColumn": "CFO_TYPE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "type": "calculated",
            "name": "PARENT_CFO_ID",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE(CFO[CFO_ID],CFO[CFO_NAME], CFO[CFO_PARENT_NAME] )",
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemPath",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "PATH(CFO[CFO_ID], CFO[PARENT_CFO_ID])"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "UtemDepth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              " PATHLENGTH(CFO[ItemPath])",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              " LOOKUPVALUE(CFO[CFO_NAME]",
              "                          ,CFO[CFO_ID]",
              "                          ,PATHITEM(CFO[ItemPath],1,INTEGER)",
              "    )",
              "    "
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              " LOOKUPVALUE(CFO[CFO_NAME]",
              "                          ,CFO[CFO_ID]",
              "                          ,PATHITEM(CFO[ItemPath],2,INTEGER)",
              "    )",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              " LOOKUPVALUE(CFO[CFO_NAME]",
              "                          ,CFO[CFO_ID]",
              "                          ,PATHITEM(CFO[ItemPath],3,INTEGER)",
              "    )",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemSort",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CFO[CFO_NAME]",
            "displayFolder": "HIDDEN"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_DIM_CFO = Source{[Schema=\"dbo\",Item=\"DIM_CFO\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DIM_CFO,{\"LOAD_TIME\", \"LOAD_DATE\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "CFO_HIERARCHY",
            "hideMembers": "hideBlankMembers",
            "levels": [
              {
                "name": "ItemLev1",
                "ordinal": 0,
                "column": "ItemLev1"
              },
              {
                "name": "ItemLev2",
                "ordinal": 1,
                "column": "ItemLev2"
              },
              {
                "name": "ItemLev3",
                "ordinal": 2,
                "column": "ItemLev3"
              }
            ]
          }
        ]
      },
      {
        "name": "MONTH",
        "columns": [
          {
            "name": "YEAR_ID",
            "dataType": "int64",
            "sourceColumn": "YEAR_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_ID",
            "dataType": "int64",
            "sourceColumn": "QUARTER_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_DESC",
            "dataType": "string",
            "sourceColumn": "QUARTER_DESC",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_ID",
            "dataType": "int64",
            "sourceColumn": "MONTH_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_DESC",
            "dataType": "string",
            "sourceColumn": "MONTH_DESC",
            "sortByColumn": "MONTH_ID",
            "displayFolder": "ATTRIBUTES"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_DIM_CALENDAR = Source{[Schema=\"dbo\",Item=\"V_DIM_CALENDAR\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_V_DIM_CALENDAR,{\"DATE_ID\", \"D_DATE\", \"DATE_DESC\", \"DOW_ID\", \"DOW_NAME\", \"DOW_DESC\", \"WEEK_ID\", \"WEEK_NUM\", \"WEEK_NAME\", \"WEEK_DESC\", \"MONTH_NUM\", \"MONTH_NAME_SHORT\", \"MONTH_NAME_FULL\", \"QUARTER_NUM\", \"QUARTER_NAME\", \"MOHTH_DAY_ID\", \"MOHTH_DAY_NAME\", \"YEAR_DAY_ID\", \"YEAR_DAY_NAME\"}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Removed Columns\", {\"YEAR_ID\", \"QUARTER_ID\", \"QUARTER_DESC\", \"MONTH_ID\", \"MONTH_DESC\"}, {{\"Count\", each _, type table [MONTH_ID=nullable number, MONTH_DESC=nullable text, QUARTER_ID=nullable number, QUARTER_DESC=nullable text, YEAR_ID=nullable number]}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Grouped Rows\",{\"Count\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"YEAR_ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Y-M",
            "levels": [
              {
                "name": "YEAR_ID",
                "ordinal": 0,
                "column": "YEAR_ID"
              },
              {
                "name": "MONTH_DESC",
                "ordinal": 1,
                "column": "MONTH_DESC"
              }
            ]
          },
          {
            "name": "Y-Q-M",
            "levels": [
              {
                "name": "YEAR_ID",
                "ordinal": 0,
                "column": "YEAR_ID"
              },
              {
                "name": "QUARTER_DESC",
                "ordinal": 1,
                "column": "QUARTER_DESC"
              },
              {
                "name": "MONTH_DESC",
                "ordinal": 2,
                "column": "MONTH_DESC"
              }
            ]
          }
        ]
      },
      {
        "name": "LAYER",
        "columns": [
          {
            "name": "LAYER_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LAYER_ID"
          },
          {
            "name": "LAYER_NAME",
            "dataType": "string",
            "sourceColumn": "LAYER_NAME"
          },
          {
            "name": "UNARY_OPERATOR",
            "dataType": "string",
            "sourceColumn": "UNARY_OPERATOR"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_DIM_LAYER = Source{[Schema=\"dbo\",Item=\"DIM_LAYER\"]}[Data]",
                "in",
                "    dbo_DIM_LAYER"
              ]
            }
          }
        ]
      },
      {
        "name": "PROFIT_LOSS",
        "columns": [
          {
            "name": "ITEM_ID",
            "dataType": "int64",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "ITEM_ID",
            "keepUniqueRows": true,
            "displayFolder": "ATTRIBUTES",
            "isDefaultLabel": true
          },
          {
            "name": "ITEM",
            "dataType": "string",
            "sourceColumn": "ITEM",
            "sortByColumn": "ITEM_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "PARENT_ITEM",
            "dataType": "string",
            "sourceColumn": "PARENT_ITEM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ITEM_TYPE",
            "dataType": "string",
            "sourceColumn": "ITEM_TYPE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "HIERARCHY_TYPE",
            "dataType": "double",
            "sourceColumn": "HIERARCHY_TYPE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "UNARY_OPERATOR",
            "dataType": "string",
            "sourceColumn": "UNARY_OPERATOR",
            "displayFolder": "HIDDEN"
          },
          {
            "name": "FORMULA",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FORMULA",
            "displayFolder": "HIDDEN"
          },
          {
            "name": "PROPORTIONAL_DRIVER",
            "dataType": "string",
            "sourceColumn": "PROPORTIONAL_DRIVER",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "type": "calculated",
            "name": "ItemPath",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH(PROFIT_LOSS[ITEM_ID], PROFIT_LOSS[PARENT_ITEM_ID])",
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemDepth",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATHLENGTH(PROFIT_LOSS[ItemPath])",
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],1,INTEGER)",
              "    )",
              "    ",
              "    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],2,INTEGER)",
              "    )    ",
              "    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],3,INTEGER)",
              "    )    ",
              "    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],4,INTEGER)",
              "    )    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],5,INTEGER)",
              "    )    ",
              "    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev6",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],6,INTEGER)",
              "    )    ",
              "",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemLev7",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM]",
              "                          ,PROFIT_LOSS[ITEM_ID]",
              "                          ,PATHITEM(PROFIT_LOSS[ItemPath],7,INTEGER)",
              "    )    ",
              "    ",
              " /*",
              "The PATHITEM function takes three arguments: the hierarchy path, ",
              "the position we want to retrieve (the 4th our case) and an optional argument ",
              "that specifies the type of the result. This type can be either text or integer.",
              "Instead of last param - INTEGER you may use =  1",
              "",
              "*/",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "PARENT_ITEM_ID",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "LOOKUPVALUE(PROFIT_LOSS[ITEM_ID]",
              "                          ,PROFIT_LOSS[ITEM]",
              "                          , PROFIT_LOSS[PARENT_ITEM]",
              "    )"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "ItemSort",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PROFIT_LOSS[PARENT_ITEM_ID]*1000 + PROFIT_LOSS[ITEM_ID]",
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "IsLeafFlag",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "IF( ISBLANK(LOOKUPVALUE(PROFIT_LOSS[PARENT_ITEM_ID],PROFIT_LOSS[PARENT_ITEM_ID],PROFIT_LOSS[ITEM_ID]) ) , 1,0)",
              "",
              "/* =======================================================",
              "another variant",
              "=  VAR CurrentItemID = PROFIT_LOSS[ITEM_ID]",
              "  VAR ChildItemCount = CALCULATE (COUNTROWS ( PROFIT_LOSS ),",
              "                                  ALL ( PROFIT_LOSS ),",
              "                                  PROFIT_LOSS[PARENT_ITEM_ID] = CurrentItemID",
              "                       )",
              "  VAR Result = ( ChildItemCount = 0 )",
              "RETURN Result",
              "",
              "==========================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel7",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 7",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "RETURN",
              "    IF ( LevelNumber = Depth, IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 ) )",
              "",
              "/*====================================================",
              "The DAX formula computing the sign at each level starts ",
              "from the most granular level  = 7  (leaf level) here. ",
              "At this most granular level, the sign to use is just ",
              "the operator converted into +1 or -1 ",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel6",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 6",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel7]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey =   PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign =  LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel5",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 5",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel6]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey =  PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign = LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel4",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 4",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel5]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey =  PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign =  LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel3",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 3",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel4]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey =  PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign = LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel2",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 2",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel3]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey  = PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign = LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "type": "calculated",
            "name": "SignToLevel1",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "VAR LevelNumber = 1",
              "VAR PrevSign = 'PROFIT_LOSS'[SignToLevel2]",
              "VAR Depth = 'PROFIT_LOSS'[ItemDepth]",
              "VAR LevelKey  = PATHITEM ( 'PROFIT_LOSS'[ItemPath], LevelNumber, INTEGER )",
              "VAR LevelSign = LOOKUPVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR], 'PROFIT_LOSS'[ITEM_ID], LevelKey )",
              "RETURN",
              "    IF (LevelNumber = Depth",
              "\t   ,IF ( 'PROFIT_LOSS'[UNARY_OPERATOR] = \"-\", -1, +1 )",
              "\t   ,IF ( LevelNumber < Depth, IF ( LevelSign = \"-\", -1, +1 ) * PrevSign )",
              "    )",
              "/*====================================================",
              "All the columns from level 1 to level 6 (except the lowest level = 7) ",
              "should follow a similar pattern, though for each level ",
              "the DAX expression must consider the sign at the more granular, ",
              "adjacent level (stored in the PrevSign variable) and invert ",
              "the result when that level shows a “-“ sign, as shown in the column for level 6:",
              "=====================================================*/"
            ],
            "displayFolder": "HIDDEN"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_DIM_PROFIT_LOSS = Source{[Schema=\"dbo\",Item=\"DIM_PROFIT_LOSS\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DIM_PROFIT_LOSS,{\"LOAD_TIME\", \"LOAD_DATE\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"[\",\"[PROFIT_LOSS].[PARENT_ITEM].&[\",Replacer.ReplaceText,{\"FORMULA\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Replaced Value\",{{\"ITEM_ID\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "CurrentItemDepth",
            "expression": [
              "",
              "   ISFILTERED ( 'PROFIT_LOSS'[ItemLev1] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev2] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev3] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev4] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev5] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev6] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev7] )"
            ],
            "isHidden": true
          },
          {
            "name": "MaxItemDepth",
            "expression": " MAX ( 'PROFIT_LOSS'[ItemDepth] )",
            "isHidden": true
          },
          {
            "name": "MinItemDepth",
            "expression": " MIN ( 'PROFIT_LOSS'[ItemDepth] )",
            "isHidden": true
          },
          {
            "name": "ItemUnaryOperator",
            "expression": [
              "",
              " VAR CurrentLevel = [Sum2 of CurrentItemDepth]",
              " RETURN",
              "   IF (CurrentLevel = [Sum2 of MaxItemDepth]",
              "      ,CALCULATE (",
              "                  IF ( HASONEVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR] )",
              "\t\t\t\t     , VAR Operator =  VALUES ( 'PROFIT_LOSS'[UNARY_OPERATOR] )",
              "                       RETURN IF ( Operator = \"-\", \"–\", Operator )",
              "                  ), 'PROFIT_LOSS'[ItemDepth] = CurrentLevel",
              "      )",
              "   )"
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "PARENT-ITEM",
            "hideMembers": "hideBlankMembers",
            "levels": [
              {
                "name": "ItemLev1",
                "ordinal": 0,
                "column": "ItemLev1"
              },
              {
                "name": "ItemLev2",
                "ordinal": 1,
                "column": "ItemLev2"
              },
              {
                "name": "ItemLev3",
                "ordinal": 2,
                "column": "ItemLev3"
              },
              {
                "name": "ItemLev4",
                "ordinal": 3,
                "column": "ItemLev4"
              },
              {
                "name": "ItemLev5",
                "ordinal": 4,
                "column": "ItemLev5"
              },
              {
                "name": "ItemLev6",
                "ordinal": 5,
                "column": "ItemLev6"
              },
              {
                "name": "ItemLev7",
                "ordinal": 6,
                "column": "ItemLev7"
              }
            ]
          },
          {
            "name": "DRIVER-ITEM",
            "hideMembers": "hideBlankMembers",
            "levels": [
              {
                "name": "PROPORTIONAL_DRIVER",
                "ordinal": 0,
                "column": "PROPORTIONAL_DRIVER"
              },
              {
                "name": "ITEM",
                "ordinal": 1,
                "column": "ITEM"
              }
            ]
          }
        ]
      },
      {
        "name": "_FCT_CFO",
        "columns": [
          {
            "name": "PNL_ITEM",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PNL_ITEM"
          },
          {
            "name": "CFO_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CFO_NAME"
          },
          {
            "name": "MONTH_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MONTH_ID"
          },
          {
            "name": "VERSION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "VERSION"
          },
          {
            "name": "LAYER_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "LAYER_ID"
          },
          {
            "name": "CFO_AMOUNT",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CFO_AMOUNT"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_FCT_CFO = Source{[Schema=\"dbo\",Item=\"FCT_CFO\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_FCT_CFO,{\"ROW_ID\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"PNL_AMOUNT\", \"CFO_AMOUNT\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of CFO_AMOUNT",
            "expression": "SUM('_FCT_CFO'[CFO_AMOUNT])"
          },
          {
            "name": "Sum of CFO_AMOUNT_SIGNED",
            "expression": [
              "",
              " IF ( [Sum2 of  MinItemDepth] >= [Sum2 of CurrentItemDepth]",
              "    , SWITCH ([Sum2 of CurrentItemDepth]",
              "                    , 1, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel1]), 'PROFIT_LOSS'[SignToLevel1] * [Sum2 of  CFO AMOUNT] )",
              "                    , 2, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel2]), 'PROFIT_LOSS'[SignToLevel2] * [Sum2 of  CFO AMOUNT] )",
              "                    , 3, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel3]), 'PROFIT_LOSS'[SignToLevel3] * [Sum2 of  CFO AMOUNT] )",
              "                    , 4, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel4]), 'PROFIT_LOSS'[SignToLevel4] * [Sum2 of  CFO AMOUNT] )",
              "                    , 5, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel5]), 'PROFIT_LOSS'[SignToLevel5] * [Sum2 of  CFO AMOUNT] )",
              "                     , 6, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel6]), 'PROFIT_LOSS'[SignToLevel6] * [Sum2 of  CFO AMOUNT] )",
              "                     , 7, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel7]), 'PROFIT_LOSS'[SignToLevel7] * [Sum2 of  CFO AMOUNT] )",
              "     )",
              " )"
            ],
            "isHidden": true
          },
          {
            "name": "Sum of CFO_AMOUNT_DataMember",
            "expression": [
              " CALCULATE( SUM('_FCT_CFO'[CFO_AMOUNT])",
              "                        ,FILTER('PROFIT_LOSS', 'PROFIT_LOSS'[ItemDepth] = [Sum2 of  MinItemDepth]))",
              "/*",
              "simulation of DataMember propery that exists in SSAS Multi in Tabular Model (that does NOT have this Proiperty)",
              "see:  https://gbrueckl.wordpress.com/2013/07/26/dax-vs-mdx-datamembers-in-parent-child-hierarchies/",
              "",
              "[CFO AMOUNT DataMember (ver2)]:= CALCULATE(",
              "SUM('Sales Quota'[Sales Amount Quota])",
              "   , FILTER(VALUES('PROFIT_LOSS'[ItemDepth])",
              "           ,'PROFIT_LOSS'[ItemDepth] = MIN('PROFIT_LOSS'[ItemDepth])))",
              "*/"
            ],
            "isHidden": true
          }
        ]
      },
      {
        "name": "_MEASURES_",
        "description": "table to store measure group",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "DummyColumn",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{0} "
            }
          }
        ],
        "measures": [
          {
            "name": "Sum2 of  CFO AMOUNT",
            "expression": "SUM('_FCT_CFO'[CFO_AMOUNT])"
          },
          {
            "name": "Sum2 of CurrentItemDepth",
            "expression": [
              "",
              "   ISFILTERED ( 'PROFIT_LOSS'[ItemLev1] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev2] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev3] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev4] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev5] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev6] )",
              " + ISFILTERED ( 'PROFIT_LOSS'[ItemLev7] )"
            ],
            "isHidden": true,
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Sum2 of MaxItemDepth",
            "expression": " MAX ( 'PROFIT_LOSS'[ItemDepth] )",
            "isHidden": true,
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Sum2 of  MinItemDepth",
            "expression": " MIN ( 'PROFIT_LOSS'[ItemDepth] )",
            "isHidden": true,
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Sum2 of  ItemUnaryOperator",
            "expression": [
              "",
              " VAR CurrentLevel = [Sum2 of CurrentItemDepth]",
              " RETURN",
              "   IF (CurrentLevel = [Sum2 of MaxItemDepth]",
              "      ,CALCULATE (",
              "                  IF ( HASONEVALUE ( 'PROFIT_LOSS'[UNARY_OPERATOR] )",
              "\t\t\t\t     , VAR Operator =  VALUES ( 'PROFIT_LOSS'[UNARY_OPERATOR] )",
              "                       RETURN IF ( Operator = \"-\", \"–\", Operator )",
              "                  ), 'PROFIT_LOSS'[ItemDepth] = CurrentLevel",
              "      )",
              "   )"
            ],
            "isHidden": true,
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Sum2 of  CFO AMOUNT SIGNED",
            "expression": [
              "",
              " IF ( [Sum2 of  MinItemDepth] >= [Sum2 of CurrentItemDepth]",
              "    , SWITCH ([Sum2 of CurrentItemDepth]",
              "\t         , 1, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel1]), 'PROFIT_LOSS'[SignToLevel1] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 2, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel2]), 'PROFIT_LOSS'[SignToLevel2] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 3, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel3]), 'PROFIT_LOSS'[SignToLevel3] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 4, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel4]), 'PROFIT_LOSS'[SignToLevel4] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 5, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel5]), 'PROFIT_LOSS'[SignToLevel5] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 6, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel6]), 'PROFIT_LOSS'[SignToLevel6] * [Sum2 of  CFO AMOUNT] )",
              "\t\t\t , 7, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel7]), 'PROFIT_LOSS'[SignToLevel7] * [Sum2 of  CFO AMOUNT] )",
              "     )",
              " )"
            ]
          },
          {
            "name": "Sum2 of  CFO AMOUNT DataMember",
            "expression": [
              " CALCULATE( SUM('_FCT_CFO'[CFO_AMOUNT])",
              "                        ,FILTER('PROFIT_LOSS', 'PROFIT_LOSS'[ItemDepth] = [Sum2 of  MinItemDepth]))",
              "/*",
              "simulation of DataMember propery that exists in SSAS Multi in Tabular Model (that does NOT have this Proiperty)",
              "see:  https://gbrueckl.wordpress.com/2013/07/26/dax-vs-mdx-datamembers-in-parent-child-hierarchies/",
              "",
              "[CFO AMOUNT DataMember (ver2)]:= CALCULATE(",
              "SUM('Sales Quota'[Sales Amount Quota])",
              "   , FILTER(VALUES('PROFIT_LOSS'[ItemDepth])",
              "           ,'PROFIT_LOSS'[ItemDepth] = MIN('PROFIT_LOSS'[ItemDepth])))",
              "*/"
            ],
            "isHidden": true
          },
          {
            "name": "Sum2 of  PNL AMOUNT",
            "expression": [
              " CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT])",
              "                                                 ,USERELATIONSHIP('_FCT_PROFIT_LOSS'[MONTH_ID], 'MONTH'[MONTH_ID])",
              "                                                 ,USERELATIONSHIP('_FCT_PROFIT_LOSS'[PNL_ITEM], 'PROFIT_LOSS'[ITEM])",
              "                                                 ,USERELATIONSHIP('_FCT_PROFIT_LOSS'[LAYER_ID], 'LAYER'[LAYER_ID])",
              "                                                 //,USERELATIONSHIP('FCT_PROFIT_LOSS'[VERSION] , 'VERSION'[VERSION])",
              "                             )",
              "                                      ",
              " /*=================================================================",
              " //This is correct",
              "PNL AMOUNT:= CALCULATE(SUM('FCT_PROFIT_LOSS'[PNL_AMOUNT])",
              "                                                 ,USERELATIONSHIP('FCT_PROFIT_LOSS'[MONTH_ID], 'MONTH'[MONTH_ID])",
              "                                                 ,USERELATIONSHIP('FCT_PROFIT_LOSS'[PNL_ITEM], 'PROFIT_LOSS'[ITEM])",
              "                                                 ,USERELATIONSHIP('FCT_PROFIT_LOSS'[LAYER_ID], 'LAYER'[LAYER_ID])",
              "                                                 //,USERELATIONSHIP('FCT_PROFIT_LOSS'[VERSION] , 'VERSION'[VERSION])",
              "                             )",
              "                                                 ",
              "                                                 ",
              "----------------------------- below is not corrcet- al PL-items = 15 insted of only Departures = 15---------------------",
              " PNL AMOUNT:= SUM('FCT_PROFIT_LOSS'[PNL_AMOUNT])",
              "",
              "================================================================== */"
            ]
          },
          {
            "name": "Sum2 of  BH",
            "expression": [
              "  ",
              "IF(SELECTEDVALUE('PROFIT_LOSS'[ITEM]) =\"BH\"   &&",
              "   SELECTEDVALUE('VERSION'[VERSION] ) =\"FCST\" &&",
              "   SELECTEDVALUE('LAYER'[LAYER_NAME]) =\"IS_DATA_LAYER\" ",
              "   --------------------- THEN -------------------------------------------",
              "  ,CALCULATE (SUM('_FCT_SCHEDULE_PTP'[BH])",
              "             ,TREATAS(VALUES('PATH'[PATH_KEY]),    'FLIGHT'[FLT_DESC])",
              "             ,TREATAS(VALUES('CALENDAR'[MONTH_ID]),'MONTH'[MONTH_ID])",
              "             --,USERELATIONSHIP('CALENDAR'[MONTH_ID],   'MONTH'[MONTH_ID]) ",
              "             --,USERELATIONSHIP('CALENDAR'[QUARTER_ID], 'MONTH'[QUARTER_ID]) ",
              "             --,USERELATIONSHIP('CALENDAR'[YEAR_ID],    'MONTH'[YEAR_ID]) ",
              "  )",
              "  ----------------------- ELSE--------------------------------------------",
              "  ,[Sum2 of  PNL AMOUNT])"
            ]
          }
        ]
      },
      {
        "name": "FLIGHT",
        "columns": [
          {
            "name": "AIRLINE",
            "dataType": "string",
            "sourceColumn": "AIRLINE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_NUM",
            "dataType": "string",
            "sourceColumn": "FLT_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ORIG",
            "dataType": "string",
            "sourceColumn": "ORIG",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DSTN",
            "dataType": "string",
            "sourceColumn": "DSTN",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_DESC",
            "dataType": "string",
            "sourceColumn": "FLT_DESC",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "HAUL",
            "dataType": "string",
            "sourceColumn": "HAUL",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_INT_DOM",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_INT_DOM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_SCH_CHR",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_SCH_CHR",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_PSN_CAR",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_PSN_CAR",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_OWH_OAL",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_OWH_OAL",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "COUNTRY_TURNOVER",
            "dataType": "string",
            "sourceColumn": "COUNTRY_TURNOVER",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DEST_GROUP",
            "dataType": "string",
            "sourceColumn": "DEST_GROUP",
            "displayFolder": "ATTRIBUTES"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_DIM_FLIGHT = Source{[Schema=\"dbo\",Item=\"DIM_FLIGHT\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DIM_FLIGHT,{\"LOAD_TIME\", \"LOAD_DATE\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "TYPE-COUNTRY-FLT",
            "levels": [
              {
                "name": "TYPE",
                "ordinal": 0,
                "column": "FLT_TYPE_INT_DOM"
              },
              {
                "name": "COUNTRY",
                "ordinal": 1,
                "column": "COUNTRY_TURNOVER"
              },
              {
                "name": "FLT",
                "ordinal": 2,
                "column": "FLT_DESC"
              }
            ]
          }
        ]
      },
      {
        "name": "_FCT_PROFIT_LOSS",
        "columns": [
          {
            "name": "PNL_ITEM",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PNL_ITEM"
          },
          {
            "name": "FLIGHT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FLIGHT"
          },
          {
            "name": "MONTH_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MONTH_ID"
          },
          {
            "name": "VERSION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "VERSION"
          },
          {
            "name": "PNL_AMOUNT",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "PNL_AMOUNT"
          },
          {
            "name": "CELL_PROP_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CELL_PROP_ID"
          },
          {
            "name": "ROW_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROW_ID"
          },
          {
            "type": "calculated",
            "name": "LAYER_ID",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "0"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_FCT_PROFIT_LOSS = Source{[Schema=\"dbo\",Item=\"FCT_PROFIT_LOSS\"]}[Data]",
                "in",
                "    dbo_FCT_PROFIT_LOSS"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of PNL_AMOUNT",
            "expression": [
              "",
              "VAR ItemValue =",
              " SWITCH(SELECTEDVALUE('PROFIT_LOSS'[ITEM])",
              "          ,\"BH\",              SUM('_FCT_SCHEDULE_PTP'[BH]) ",
              "          ,\"Departures\", SUM('_FCT_SCHEDULE_PTP'[DEPARTURES]) ",
              "          ,\"Seats\",          SUM('_FCT_SCHEDULE_PTP'[SEATS]) ",
              "          ,\"Seats C\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_C]) ",
              "          ,\"Seats Y\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_S]) ",
              "          ,\"Seats Y+\",     SUM('_FCT_SCHEDULE_PTP'[SEATS_W]) ",
              "          ,\"KM\",               SUM('_FCT_SCHEDULE_PTP'[DISTANCE]) ",
              "        --, SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]) ",
              "         --============= FORMULAS ============================ ",
              "          ,\"Pax Load Factor\",   [Pax Load Factor]",
              "          ,\"Pax per Sector\",     [Pax per Sector]",
              "          ,\"KM per Sector\",      [KM per Sector]",
              "          ,\"Seats per Sector\",  [Seats per Sector]",
              "          ,\"Yield per RPK (c)\",  [Yield per RPK (c)]",
              "          ,\"ASK (mills)\",            [ASK (mills)]",
              "          ,\"RPK (mills)\",            [RPK (mills)]",
              "          ,\"RTK (Pax)\" ,           [RTK (Pax)]",
              "          ,\"Fuel(t)/BH\",            [Fuel(t)/BH]",
              "          ,\"C1\" ,                       [C1]",
              "          ,\"C2\" ,                       [C2]",
              "          ,\"EBIT\",                     [EBIT]",
              "         --=====================================================",
              " )",
              "          ",
              "RETURN",
              "IF(SELECTEDVALUE('VERSION'[VERSION] ) =\"FCST\" &&  SELECTEDVALUE('LAYER'[LAYER_NAME]) =\"IS_DATA_LAYER\" ",
              "    ,CALCULATE(ItemValue ",
              "                        ,TREATAS(VALUES('PATH'[PATH_KEY]),'FLIGHT'[FLT_DESC]) ",
              "                        ,TREATAS(VALUES('CALENDAR'[MONTH_ID]),'MONTH'[MONTH_ID]) ",
              "                        ,TREATAS(VALUES('CALENDAR'[QUARTER_ID]),'MONTH'[QUARTER_ID]) \t\t   ",
              "                        ,TREATAS(VALUES('CALENDAR'[YEAR_ID]),'MONTH'[YEAR_ID]) \t\t",
              "    )",
              "  , SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]) ",
              ")",
              "",
              "",
              "/*========================= OLD ===============================",
              "",
              "Sum of PNL_AMOUNT:=",
              "VAR ItemValue =",
              " SWITCH(SELECTEDVALUE('PROFIT_LOSS'[ITEM])",
              "          ,\"BH\",              SUM('_FCT_SCHEDULE_PTP'[BH]) ",
              "          ,\"Departures\", SUM('_FCT_SCHEDULE_PTP'[DEPARTURES]) ",
              "          ,\"Seats\",          SUM('_FCT_SCHEDULE_PTP'[SEATS]) ",
              "          ,\"Seats C\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_C]) ",
              "          ,\"Seats Y\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_S]) ",
              "          ,\"Seats Y+\",     SUM('_FCT_SCHEDULE_PTP'[SEATS_W]) ",
              "          ,\"KM\",               SUM('_FCT_SCHEDULE_PTP'[DISTANCE]) ",
              "        --, SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]) ",
              "         --============= FORMULAS ============================ ",
              "          ,\"Pax Load Factor\",   [Pax Load Factor]",
              "          ,\"Pax per Sector\",     [Pax per Sector]",
              "          ,\"KM per Sector\",      [KM per Sector]",
              "          ,\"Seats per Sector\",  [Seats per Sector]",
              "          ,\"Yield per RPK (c)\",  [Yield per RPK (c)]",
              "          ,\"ASK (mills)\",            [ASK (mills)]",
              "          ,\"RPK (mills)\",            [RPK (mills)]",
              "          ,\"RTK (Pax)\" ,           [RTK (Pax)]",
              "          ,\"Fuel(t)/BH\",            [Fuel(t)/BH]",
              "          ,\"C1\" ,                       [C1]",
              "          ,\"C2\" ,                       [C2]",
              "          ,\"EBIT\",                     [EBIT]",
              "         --=====================================================",
              " )",
              "          ",
              "RETURN",
              "IF(SELECTEDVALUE('VERSION'[VERSION] ) =\"FCST\" &&  SELECTEDVALUE('LAYER'[LAYER_NAME]) =\"IS_DATA_LAYER\" ",
              "  ,CALCULATE(ItemValue  ,TREATAS(VALUES('PATH'[PATH_KEY]),    'FLIGHT'[FLT_DESC]) ,TREATAS(VALUES('CALENDAR'[MONTH_ID]),'MONTH'[MONTH_ID])    )",
              "  ,SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]) ",
              ")",
              "",
              "=============================================================*/"
            ]
          },
          {
            "name": "Sum of PNL_AMOUNT_SIGNED",
            "expression": [
              " ",
              "",
              " IF ( [MinItemDepth] >= [CurrentItemDepth]",
              "    , SWITCH ([CurrentItemDepth]",
              "                     , 1, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel1]), 'PROFIT_LOSS'[SignToLevel1] * [Sum of PNL_AMOUNT] )",
              "                     , 2, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel2]), 'PROFIT_LOSS'[SignToLevel2] * [Sum of PNL_AMOUNT] )",
              "                     , 3, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel3]), 'PROFIT_LOSS'[SignToLevel3] * [Sum of PNL_AMOUNT] )",
              "                     , 4, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel4]), 'PROFIT_LOSS'[SignToLevel4] * [Sum of PNL_AMOUNT] )",
              "                     , 5, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel5]), 'PROFIT_LOSS'[SignToLevel5] * [Sum of PNL_AMOUNT] )",
              "                     , 6, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel6]), 'PROFIT_LOSS'[SignToLevel6] * [Sum of PNL_AMOUNT] )",
              "                     , 7, SUMX (VALUES ('PROFIT_LOSS'[SignToLevel7]), 'PROFIT_LOSS'[SignToLevel7] * [Sum of PNL_AMOUNT] )",
              "     )",
              " )",
              " "
            ]
          },
          {
            "name": "RPK (mills)",
            "expression": [
              "",
              "VAR KM  = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"KM\")             -- returns NULL",
              "VAR PAX = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"PAX\")            -- returns NULL",
              "VAR DEP = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Departures\")  -- =  15 vause it's the only row in table \"FCT_PROFIT_LOSS\"",
              "RETURN  ",
              "DIVIDE(KM*PAX,DEP)/1000000",
              "",
              "-- RPK (mills) = [KM] * [PAX] /[Departures] /1000000",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "ASK (mills)",
            "expression": [
              "",
              "VAR KM  = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"KM\") ",
              "VAR STS = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Seats\") ",
              "VAR DEP = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Departures\") ",
              "RETURN",
              "DIVIDE(KM*STS,DEP)/1000000",
              "",
              "-- ASK (mills)= [KM] * [Seats] /[Departures] /1000000",
              "",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "RTK (Pax)",
            "expression": [
              "\t[RPK (mills)] * 90",
              "",
              "-- RTK (Pax) = [RPK (mills)] * 90",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Fuel(t)/BH",
            "expression": [
              "  ",
              "VAR FL  = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Fuel(t)\") ",
              "VAR BH = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"BH\") ",
              "RETURN DIVIDE(FL,BH)",
              "",
              "--Fuel(t)/BH = [Fuel(t)] /[BH] ",
              "",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Pax Load Factor",
            "expression": [
              " DIVIDE([RPK (mills)],[ASK (mills)])",
              "",
              "-- Pax Load Factor = [RPK (mills)]/[ASK (mills)]",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Pax per Sector",
            "expression": [
              " ",
              "VAR PAX = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"PAX\") ",
              "VAR DEP = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Departures\") ",
              "RETURN DIVIDE(PAX,DEP)",
              "",
              "--  Pax per Sector = [PAX]/[Departures] ",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "KM per Sector",
            "expression": [
              " ",
              "VAR KM   = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"KM\") ",
              "VAR DEP = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Departures\") ",
              "RETURN DIVIDE(KM,DEP)",
              "",
              "-- KM per Sector = [KM]/[Departures]",
              ""
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Seats per Sector",
            "expression": [
              " ",
              "VAR KM = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"KM\") ",
              "RETURN DIVIDE([ASK (mills)],KM)",
              "",
              "--Seats per Sector = [ASK (mills)] /[KM]"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Yield per RPK (c)",
            "expression": [
              " ",
              "VAR REV= CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"PASSENGER REVENUE\") ",
              "RETURN DIVIDE(REV,[RPK (mills)] )",
              " ",
              "--Yield per RPK (c)\t= [PASSENGER REVENUE] /[RPK (mills)] /10000"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "C1",
            "expression": [
              " ",
              "VAR REV = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"REVENUE\") ",
              "VAR TOT = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"TOTAL VARIABLE COSTS\") ",
              "RETURN  REV - TOT",
              "",
              "--C1 = [REVENUE] - [TOTAL VARIABLE COSTS]"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "C2",
            "expression": [
              " ",
              "VAR REV = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"REVENUE\") ",
              "VAR TOT = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"TOTAL VARIABLE COSTS\")",
              "VAR FXD = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"TOTAL FIXED COSTS\")",
              "RETURN  REV - TOT - FXD",
              "--C2 = [REVENUE] - [TOTAL VARIABLE COSTS] - [TOTAL FIXED COSTS]"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "EBIT",
            "expression": [
              " ",
              "VAR REV = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"REVENUE\") ",
              "VAR TOT = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"TOTAL VARIABLE COSTS\")",
              "VAR FXD = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"TOTAL FIXED COSTS\")",
              "VAR ADM = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"GENERAL AND ADMIN EXPENCES\") ",
              "RETURN  REV - TOT - FXD - ADM",
              "",
              "--EBIT= [REVENUE] - [TOTAL VARIABLE COSTS] - [TOTAL FIXED COSTS] - [GENERAL AND ADMIN EXPENCES]"
            ],
            "displayFolder": "HIDDEN"
          },
          {
            "name": "Sum2 of PNL_AMOUNT",
            "expression": [
              "",
              "IF(SELECTEDVALUE('VERSION'[VERSION] ) =\"FCST\" &&  SELECTEDVALUE('LAYER'[LAYER_NAME]) =\"IS_DATA_LAYER\" ,",
              "   VAR ItemValue =",
              "   SWITCH(SELECTEDVALUE('PROFIT_LOSS'[ITEM])",
              "          ,\"BH\",              SUM('_FCT_SCHEDULE_PTP'[BH]) ",
              "          ,\"Departures\", SUM('_FCT_SCHEDULE_PTP'[DEPARTURES]) ",
              "          ,\"Seats\",          SUM('_FCT_SCHEDULE_PTP'[SEATS]) ",
              "          ,\"Seats C\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_C]) ",
              "          ,\"Seats Y\",       SUM('_FCT_SCHEDULE_PTP'[SEATS_S]) ",
              "          ,\"Seats Y+\",     SUM('_FCT_SCHEDULE_PTP'[SEATS_W]) ",
              "          ,\"KM\",               SUM('_FCT_SCHEDULE_PTP'[DISTANCE]) ",
              "        --, SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]) ",
              "         --============= FORMULAS ============================ ",
              "          ,\"Pax Load Factor\",   [Pax Load Factor]",
              "          ,\"Pax per Sector\",     [Pax per Sector]",
              "          ,\"KM per Sector\",      [KM per Sector]",
              "          ,\"Seats per Sector\",  [Seats per Sector]",
              "          ,\"Yield per RPK (c)\",  [Yield per RPK (c)]",
              "          ,\"ASK (mills)\",            [ASK (mills)]",
              "          ,\"RPK (mills)\",            [RPK (mills)]",
              "          ,\"RTK (Pax)\" ,           [RTK (Pax)]",
              "          ,\"Fuel(t)/BH\",            [Fuel(t)/BH]",
              "          ,\"C1\" ,                       [C1]",
              "          ,\"C2\" ,                       [C2]",
              "          ,\"EBIT\",                     [EBIT]               ",
              "           , SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT])          ",
              "  )",
              "",
              "          ",
              "RETURN",
              "CALCULATE(ItemValue ",
              "         ,TREATAS(VALUES('PATH'[PATH_KEY]),'FLIGHT'[FLT_DESC]) ",
              "         ,TREATAS(VALUES('CALENDAR'[MONTH_ID]),'MONTH'[MONTH_ID]) ",
              "         ,TREATAS(VALUES('CALENDAR'[QUARTER_ID]),'MONTH'[QUARTER_ID]) \t\t   ",
              "         ,TREATAS(VALUES('CALENDAR'[YEAR_ID]),'MONTH'[YEAR_ID]) \t\t",
              "))"
            ],
            "isHidden": true
          },
          {
            "name": "KM per Sector test",
            "expression": [
              " ",
              "VAR KM   = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"KM\") ",
              "VAR DEP = CALCULATE(SUM('_FCT_PROFIT_LOSS'[PNL_AMOUNT]), 'PROFIT_LOSS'[ITEM] = \"Departures\") ",
              "RETURN DIVIDE(KM,DEP)",
              "",
              "-- KM per Sector = [KM]/[Departures]"
            ]
          }
        ]
      },
      {
        "name": "_FCT_SCHEDULE_PTP",
        "columns": [
          {
            "name": "FLT_DESC",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FLT_DESC"
          },
          {
            "name": "FLT_DESC_OP",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FLT_DESC_OP"
          },
          {
            "name": "FLIGHT_DATE",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "FLIGHT_DATE"
          },
          {
            "name": "DEP_TIME",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DEP_TIME"
          },
          {
            "name": "ARR_TIME",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ARR_TIME"
          },
          {
            "name": "AIRCRAFT_TYPE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "AIRCRAFT_TYPE"
          },
          {
            "name": "VERSION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "VERSION"
          },
          {
            "name": "DEPARTURES",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DEPARTURES"
          },
          {
            "name": "DISTANCE",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DISTANCE"
          },
          {
            "name": "BH",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BH"
          },
          {
            "name": "SEATS",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SEATS"
          },
          {
            "name": "SEATS_C",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SEATS_C"
          },
          {
            "name": "SEATS_W",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SEATS_W"
          },
          {
            "name": "SEATS_S",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SEATS_S"
          },
          {
            "name": "LAYER_ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LAYER_ID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_FCT_SCHEDULE_FLIGHT_PTP = Source{[Schema=\"dbo\",Item=\"V_FCT_SCHEDULE_FLIGHT_PTP\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_V_FCT_SCHEDULE_FLIGHT_PTP, \"LAYER_ID\", each 0)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of BH",
            "expression": " SUM(_FCT_SCHEDULE_PTP[BH])"
          },
          {
            "name": "Sum of SEATS",
            "expression": " SUM(_FCT_SCHEDULE_PTP[SEATS])"
          },
          {
            "name": "Sum of SEATS_C",
            "expression": " SUM(_FCT_SCHEDULE_PTP[SEATS_C])"
          },
          {
            "name": "Sum of SEATS_W",
            "expression": " SUM(_FCT_SCHEDULE_PTP[SEATS_W])"
          },
          {
            "name": "Sum of SEATS_S",
            "expression": " SUM(_FCT_SCHEDULE_PTP[SEATS_S])"
          },
          {
            "name": "Sum of DISTANCE",
            "expression": " SUM(_FCT_SCHEDULE_PTP[DISTANCE])"
          },
          {
            "name": "Sum of DEPARTURES",
            "expression": " SUM(_FCT_SCHEDULE_PTP[DEPARTURES])"
          }
        ]
      },
      {
        "name": "CALENDAR",
        "columns": [
          {
            "name": "DATE_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "D_DATE",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "D_DATE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DATE_DESC",
            "dataType": "string",
            "sourceColumn": "DATE_DESC",
            "sortByColumn": "DATE_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DAY_OF_WEEK",
            "dataType": "int64",
            "sourceColumn": "DOW_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DAY_OF_WEEK_NAME_SHORT",
            "dataType": "string",
            "sourceColumn": "DOW_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DAY_OF_WEEK_NAME_FULL",
            "dataType": "string",
            "sourceColumn": "DOW_DESC",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "WEEK_KEY",
            "dataType": "int64",
            "sourceColumn": "WEEK_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "WEEK_NUM",
            "dataType": "int64",
            "sourceColumn": "WEEK_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "WEEK_NAME",
            "dataType": "string",
            "sourceColumn": "WEEK_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "WEEK_DESC",
            "dataType": "string",
            "sourceColumn": "WEEK_DESC",
            "sortByColumn": "WEEK_KEY",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_ID",
            "dataType": "int64",
            "sourceColumn": "MONTH_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_NUM",
            "dataType": "int64",
            "sourceColumn": "MONTH_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_NAME_SHORT",
            "dataType": "string",
            "sourceColumn": "MONTH_NAME_SHORT",
            "sortByColumn": "MONTH_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_NAME_FULL",
            "dataType": "string",
            "sourceColumn": "MONTH_NAME_FULL",
            "sortByColumn": "MONTH_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MONTH_DESC",
            "dataType": "string",
            "sourceColumn": "MONTH_DESC",
            "sortByColumn": "MONTH_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_ID",
            "dataType": "int64",
            "sourceColumn": "QUARTER_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_NUM",
            "dataType": "int64",
            "sourceColumn": "QUARTER_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_NAME",
            "dataType": "string",
            "sourceColumn": "QUARTER_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUARTER_DESC",
            "dataType": "string",
            "sourceColumn": "QUARTER_DESC",
            "sortByColumn": "QUARTER_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "YEAR_ID",
            "dataType": "int64",
            "sourceColumn": "YEAR_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DAY_OF_MONTH",
            "dataType": "int64",
            "sourceColumn": "MOHTH_DAY_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "MOHTH_DAY_NAME",
            "dataType": "string",
            "sourceColumn": "MOHTH_DAY_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DAY_OF_YEAR",
            "dataType": "int64",
            "sourceColumn": "YEAR_DAY_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "YEAR_DAY_NAME",
            "dataType": "string",
            "sourceColumn": "YEAR_DAY_NAME",
            "displayFolder": "ATTRIBUTES"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_DIM_CALENDAR = Source{[Schema=\"dbo\",Item=\"V_DIM_CALENDAR\"]}[Data]",
                "in",
                "    dbo_V_DIM_CALENDAR"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Y-Q-M-D",
            "levels": [
              {
                "name": "YEAR",
                "ordinal": 0,
                "column": "YEAR_ID"
              },
              {
                "name": "MONTH",
                "ordinal": 2,
                "column": "MONTH_DESC"
              },
              {
                "name": "QUARTER",
                "ordinal": 1,
                "column": "QUARTER_DESC"
              },
              {
                "name": "DATE",
                "ordinal": 3,
                "column": "DATE_DESC"
              }
            ]
          },
          {
            "name": "Y-W-D",
            "levels": [
              {
                "name": "YEAR",
                "ordinal": 0,
                "column": "YEAR_ID"
              },
              {
                "name": "WEEK",
                "ordinal": 1,
                "column": "WEEK_DESC"
              },
              {
                "name": "DATE",
                "ordinal": 2,
                "column": "DATE_DESC"
              }
            ]
          },
          {
            "name": "Y-M",
            "levels": [
              {
                "name": "YEAR_ID",
                "ordinal": 0,
                "column": "YEAR_ID"
              },
              {
                "name": "MONTH",
                "ordinal": 1,
                "column": "MONTH_DESC"
              }
            ]
          }
        ]
      },
      {
        "name": "PATH",
        "columns": [
          {
            "name": "PATH_KEY",
            "dataType": "string",
            "sourceColumn": "PATH_KEY",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_PATH_ORG",
            "dataType": "string",
            "sourceColumn": "FLT_PATH_ORG",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_PATH_DST",
            "dataType": "string",
            "sourceColumn": "FLT_PATH_DST",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ORG_AIRPORT",
            "dataType": "string",
            "sourceColumn": "ORG_AIRPORT",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DST_AIRPORT",
            "dataType": "string",
            "sourceColumn": "DST_AIRPORT",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "COEF_LOGIC",
            "dataType": "double",
            "sourceColumn": "COEF_LOGIC",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "OND",
            "dataType": "string",
            "sourceColumn": "OND",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "PATH_TYPE",
            "dataType": "string",
            "sourceColumn": "PATH_TYPE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "PATH_VIA_AIRPORT",
            "dataType": "string",
            "sourceColumn": "PATH_VIA_AIRPORT",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ORG_COUNTRY_CODE",
            "dataType": "string",
            "sourceColumn": "ORG_COUNTRY_CODE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ORG_COUNTRY_NAME",
            "dataType": "string",
            "sourceColumn": "ORG_COUNTRY_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "ORG_REGION_CODE",
            "dataType": "string",
            "sourceColumn": "ORG_REGION_CODE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DST_COUNTRY_CODE",
            "dataType": "string",
            "sourceColumn": "DST_COUNTRY_CODE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DST_COUNTRY_NAME",
            "dataType": "string",
            "sourceColumn": "DST_COUNTRY_NAME",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DST_REGION_CODE",
            "dataType": "string",
            "sourceColumn": "DST_REGION_CODE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_NUM",
            "dataType": "string",
            "sourceColumn": "FLT_NUM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "HAUL",
            "dataType": "string",
            "sourceColumn": "HAUL",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_INT_DOM",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_INT_DOM",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_SCH_CHR",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_SCH_CHR",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_PSN_CAR",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_PSN_CAR",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "FLT_TYPE_OWH_OAL",
            "dataType": "string",
            "sourceColumn": "FLT_TYPE_OWH_OAL",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "COUNTRY_TURNOVER",
            "dataType": "string",
            "sourceColumn": "COUNTRY_TURNOVER",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "DEST_GROUP",
            "dataType": "string",
            "sourceColumn": "DEST_GROUP",
            "displayFolder": "ATTRIBUTES"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.NestedJoin(DIM_PATH, {\"ORG_AIRPORT\"}, DIM_AIRPORT_ORG, {\"LATITUDE\"}, \"DIM_AIRPORT_ORG\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_AIRPORT_ORG\" = Table.ExpandTableColumn(Source, \"DIM_AIRPORT_ORG\", {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}, {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded DIM_AIRPORT_ORG\",{{\"COUNTRY_CODE\", \"ORG_COUNTRY_CODE\"}, {\"COUNTRY_DESC\", \"ORG_COUNTRY_NAME\"}, {\"REGION_CODE\", \"ORG_REGION_CODE\"}, {\"ORG_DST\", \"OND\"}, {\"ORG_DST_TYPE\", \"PATH_TYPE\"}, {\"VIA_AIRPORT\", \"PATH_VIA_AIRPORT\"}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"DST_AIRPORT\"}, DIM_AIRPORT_DST, {\"AIRPORT_CODE\"}, \"DIM_AIRPORT_DST\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_AIRPORT_DST\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DIM_AIRPORT_DST\", {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}, {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded DIM_AIRPORT_DST\",{{\"COUNTRY_CODE\", \"DST_COUNTRY_CODE\"}, {\"COUNTRY_DESC\", \"DST_COUNTRY_NAME\"}, {\"REGION_CODE\", \"DST_REGION_CODE\"}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns1\", {\"PATH_KEY\"}, DIM_FLIGHT, {\"FLT_DESC\"}, \"DIM_FLIGHT\", JoinKind.LeftOuter),",
                "    #\"Expanded DIM_FLIGHT\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DIM_FLIGHT\", {\"FLT_NUM\", \"HAUL\", \"FLT_TYPE_INT_DOM\", \"FLT_TYPE_SCH_CHR\", \"FLT_TYPE_PSN_CAR\", \"FLT_TYPE_OWH_OAL\", \"COUNTRY_TURNOVER\", \"DEST_GROUP\"}, {\"FLT_NUM\", \"HAUL\", \"FLT_TYPE_INT_DOM\", \"FLT_TYPE_SCH_CHR\", \"FLT_TYPE_PSN_CAR\", \"FLT_TYPE_OWH_OAL\", \"COUNTRY_TURNOVER\", \"DEST_GROUP\"})",
                "in",
                "    #\"Expanded DIM_FLIGHT\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "TYPE-PATH",
            "levels": [
              {
                "name": "PATH_TYPE",
                "ordinal": 0,
                "column": "PATH_TYPE"
              },
              {
                "name": "PATH_KEY",
                "ordinal": 1,
                "column": "PATH_KEY"
              }
            ]
          },
          {
            "name": "ORG (REGION-COUNTRY-AIRPORT-OND-PATH)",
            "levels": [
              {
                "name": "ORG_REGION_CODE",
                "ordinal": 0,
                "column": "ORG_REGION_CODE"
              },
              {
                "name": "ORG_COUNTRY_NAME",
                "ordinal": 1,
                "column": "ORG_COUNTRY_NAME"
              },
              {
                "name": "ORG_AIRPORT",
                "ordinal": 2,
                "column": "ORG_AIRPORT"
              },
              {
                "name": "ORG_DST",
                "ordinal": 3,
                "column": "OND"
              },
              {
                "name": "PATH_KEY",
                "ordinal": 4,
                "column": "PATH_KEY"
              }
            ]
          },
          {
            "name": "DST ( REGION-COUNTY-AIRPORT-OND-PATH)",
            "levels": [
              {
                "name": "DST_REGION_CODE",
                "ordinal": 0,
                "column": "DST_REGION_CODE"
              },
              {
                "name": "DST_COUNTRY_NAME",
                "ordinal": 1,
                "column": "DST_COUNTRY_NAME"
              },
              {
                "name": "DST_AIRPORT",
                "ordinal": 2,
                "column": "DST_AIRPORT"
              },
              {
                "name": "ORG_DST",
                "ordinal": 3,
                "column": "OND"
              },
              {
                "name": "PATH_KEY",
                "ordinal": 4,
                "column": "PATH_KEY"
              }
            ]
          }
        ]
      },
      {
        "name": "_FCT_SCHEDULE_TRANSIT",
        "columns": [
          {
            "name": "PATH_KEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PATH_KEY"
          },
          {
            "name": "FLIGHT_DATE",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "FLIGHT_DATE"
          },
          {
            "name": "RNG_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RNG_ID"
          },
          {
            "name": "VERSION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "VERSION"
          },
          {
            "name": "COUNT_CONNECTION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "COUNT_CONNECTION"
          },
          {
            "name": "LAYER_ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LAYER_ID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_FCT_SCHEDULE_FLIGHT_TRANSIT = Source{[Schema=\"dbo\",Item=\"V_FCT_SCHEDULE_FLIGHT_TRANSIT\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_V_FCT_SCHEDULE_FLIGHT_TRANSIT, \"LAYER_ID\", each 0)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of COUNT_CONNECTION",
            "expression": " SUM(_FCT_SCHEDULE_TRANSIT[COUNT_CONNECTION])"
          }
        ]
      },
      {
        "name": "TIME_CONNECTION",
        "columns": [
          {
            "name": "RNG_ID",
            "dataType": "int64",
            "sourceColumn": "RNG_ID",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "PERIOD_HH",
            "dataType": "int64",
            "sourceColumn": "PERIOD_HH",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "TIME_RANGE",
            "dataType": "string",
            "sourceColumn": "TIME_RANGE",
            "displayFolder": "ATTRIBUTES"
          },
          {
            "name": "QUALITY_CONNECTION",
            "dataType": "string",
            "sourceColumn": "QUALITY_CONNECTION",
            "displayFolder": "ATTRIBUTES"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_V_DIM_TIME_RANGE = Source{[Schema=\"dbo\",Item=\"V_DIM_TIME_RANGE\"]}[Data]",
                "in",
                "    dbo_V_DIM_TIME_RANGE"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "TIME_RANGE (HH-RANGE)",
            "levels": [
              {
                "name": "PERIOD_HH",
                "ordinal": 0,
                "column": "PERIOD_HH"
              },
              {
                "name": "TIME_RANGE",
                "ordinal": 1,
                "column": "TIME_RANGE"
              }
            ]
          },
          {
            "name": "TIME_RANGE (QUALITY-RANGE)",
            "levels": [
              {
                "name": "QUALITY_CONNECTION",
                "ordinal": 0,
                "column": "QUALITY_CONNECTION"
              },
              {
                "name": "TIME_RANGE",
                "ordinal": 1,
                "column": "TIME_RANGE"
              }
            ]
          }
        ]
      },
      {
        "name": "_FCT_DRIVER_SHARE",
        "columns": [
          {
            "name": "PNL_ITEM",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PNL_ITEM"
          },
          {
            "name": "FLIGHT",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "FLIGHT"
          },
          {
            "name": "MONTH_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MONTH_ID"
          },
          {
            "name": "VERSION",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "VERSION"
          },
          {
            "name": "FLAG_USE_FLIGHT",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "FLAG_USE_FLIGHT"
          },
          {
            "name": "AMOUNT_FOR_ALLOCATION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AMOUNT_FOR_ALLOCATION"
          },
          {
            "name": "DRIVER_FOR_ALLOCATION",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DRIVER_FOR_ALLOCATION"
          },
          {
            "name": "DRIVER_USE_FLIGHT",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DRIVER_USE_FLIGHT"
          },
          {
            "name": "DRIVER_USE_FLIGHT_TOTAL",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DRIVER_USE_FLIGHT_TOTAL"
          },
          {
            "name": "SHARE_AMOUNT",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SHARE_AMOUNT"
          },
          {
            "name": "AMOUNT_ALLOCATED",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "AMOUNT_ALLOCATED"
          },
          {
            "name": "ROW_ID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROW_ID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ ;DWH_VC_AVT\",",
                "    dbo_FCT_DRIVER_SHARE = Source{[Schema=\"dbo\",Item=\"FCT_DRIVER_SHARE\"]}[Data]",
                "in",
                "    dbo_FCT_DRIVER_SHARE"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sum of FLAG_USE_FLIGHT",
            "expression": [
              "  SUM('_FCT_DRIVER_SHARE'[FLAG_USE_FLIGHT])",
              ""
            ]
          },
          {
            "name": "Sum of AMOUNT_FOR_ALLOCATION",
            "expression": "  SUM('_FCT_DRIVER_SHARE'[AMOUNT_FOR_ALLOCATION])"
          },
          {
            "name": "Avg of SHARE_AMOUNT",
            "expression": "  AVERAGE('_FCT_DRIVER_SHARE'[SHARE_AMOUNT])"
          },
          {
            "name": "Sum of DRIVER_FOR_ALLOCATION",
            "expression": " SUM(_FCT_DRIVER_SHARE[DRIVER_FOR_ALLOCATION])"
          },
          {
            "name": "Sum of DRIVER_USE_FLIGHT",
            "expression": " SUM(_FCT_DRIVER_SHARE[DRIVER_USE_FLIGHT])"
          },
          {
            "name": "Sum of DRIVER_USE_FLIGHT_TOTAL",
            "expression": " SUM(_FCT_DRIVER_SHARE[DRIVER_USE_FLIGHT_TOTAL])"
          },
          {
            "name": "Sum of AMOUNT_ALLOCATED",
            "expression": " SUM(_FCT_DRIVER_SHARE[AMOUNT_ALLOCATED])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "5e735e3b-6a15-4220-b791-bcd35f97730f",
        "fromTable": "_FCT_CFO",
        "fromColumn": "CFO_NAME",
        "toTable": "CFO",
        "toColumn": "CFO_NAME"
      },
      {
        "name": "2ffa6daa-a86e-44e9-acfa-c2af41b20846",
        "fromTable": "_FCT_CFO",
        "fromColumn": "MONTH_ID",
        "toTable": "MONTH",
        "toColumn": "MONTH_ID"
      },
      {
        "name": "7bd6ea08-1da6-4722-a86d-60ad5783a2f3",
        "fromTable": "_FCT_CFO",
        "fromColumn": "LAYER_ID",
        "toTable": "LAYER",
        "toColumn": "LAYER_ID"
      },
      {
        "name": "a110e67c-4801-4203-af70-8eaec4c02b33",
        "fromTable": "_FCT_CFO",
        "fromColumn": "VERSION",
        "toTable": "VERSION",
        "toColumn": "VERSION"
      },
      {
        "name": "60e28606-4440-4a8b-a4c4-d8405d52334a",
        "fromTable": "_FCT_CFO",
        "fromColumn": "PNL_ITEM",
        "toTable": "PROFIT_LOSS",
        "toColumn": "ITEM"
      },
      {
        "name": "39d4b7a2-f988-45fb-9740-a28c18eb7729",
        "fromTable": "_FCT_SCHEDULE_PTP",
        "fromColumn": "FLT_DESC",
        "toTable": "PATH",
        "toColumn": "PATH_KEY"
      },
      {
        "name": "32513ed3-7565-457e-94be-e6e778ce08bc",
        "fromTable": "_FCT_PROFIT_LOSS",
        "fromColumn": "FLIGHT",
        "toTable": "FLIGHT",
        "toColumn": "FLT_DESC"
      },
      {
        "name": "985f1b6b-2ebc-4724-a0f7-28504d6fb4a7",
        "fromTable": "_FCT_PROFIT_LOSS",
        "fromColumn": "VERSION",
        "toTable": "VERSION",
        "toColumn": "VERSION"
      },
      {
        "name": "79c7374e-af3b-4498-a3f3-e5fb1c16fafc",
        "fromTable": "_FCT_PROFIT_LOSS",
        "fromColumn": "MONTH_ID",
        "toTable": "MONTH",
        "toColumn": "MONTH_ID"
      },
      {
        "name": "2868ac6f-0eeb-4857-b784-4c505b7ebaf9",
        "fromTable": "_FCT_PROFIT_LOSS",
        "fromColumn": "PNL_ITEM",
        "toTable": "PROFIT_LOSS",
        "toColumn": "ITEM"
      },
      {
        "name": "5f35d860-fddc-4e6d-90a7-3f7c1a7c05bb",
        "fromTable": "_FCT_PROFIT_LOSS",
        "fromColumn": "LAYER_ID",
        "toTable": "LAYER",
        "toColumn": "LAYER_ID"
      },
      {
        "name": "63973f10-ecf0-42cb-80f0-ca5dd4e46a19",
        "fromTable": "_FCT_SCHEDULE_PTP",
        "fromColumn": "LAYER_ID",
        "toTable": "LAYER",
        "toColumn": "LAYER_ID"
      },
      {
        "name": "ba8be961-b5ff-4863-936e-5d5eb3d811b2",
        "fromTable": "_FCT_SCHEDULE_PTP",
        "fromColumn": "VERSION",
        "toTable": "VERSION",
        "toColumn": "VERSION"
      },
      {
        "name": "687b8f4a-7a67-486a-9c7d-f9fb867f5fdf",
        "fromTable": "_FCT_SCHEDULE_PTP",
        "fromColumn": "FLT_DESC",
        "toTable": "FLIGHT",
        "toColumn": "FLT_DESC"
      },
      {
        "name": "3a3ae448-f8fe-4dae-9b1e-7c51afd79c8c",
        "fromTable": "_FCT_SCHEDULE_PTP",
        "fromColumn": "FLIGHT_DATE",
        "toTable": "CALENDAR",
        "toColumn": "D_DATE"
      },
      {
        "name": "79d281de-cb08-4bac-b881-e95f57059aa3",
        "fromTable": "_FCT_SCHEDULE_TRANSIT",
        "fromColumn": "PATH_KEY",
        "toTable": "PATH",
        "toColumn": "PATH_KEY"
      },
      {
        "name": "512160ce-4c50-45ad-b42d-2183bffeb711",
        "fromTable": "_FCT_SCHEDULE_TRANSIT",
        "fromColumn": "LAYER_ID",
        "toTable": "LAYER",
        "toColumn": "LAYER_ID"
      },
      {
        "name": "25f89240-6dbd-4882-a0e1-28a1bf9613f0",
        "fromTable": "_FCT_SCHEDULE_TRANSIT",
        "fromColumn": "VERSION",
        "toTable": "VERSION",
        "toColumn": "VERSION"
      },
      {
        "name": "6f1e1c02-90ea-4963-9757-fcbc5e6511b6",
        "fromTable": "_FCT_SCHEDULE_TRANSIT",
        "fromColumn": "RNG_ID",
        "toTable": "TIME_CONNECTION",
        "toColumn": "RNG_ID"
      },
      {
        "name": "b901a78e-7e46-4b9f-879e-1b7307b2a001",
        "fromTable": "_FCT_SCHEDULE_TRANSIT",
        "fromColumn": "FLIGHT_DATE",
        "toTable": "CALENDAR",
        "toColumn": "D_DATE"
      },
      {
        "name": "fccef59e-230c-481b-a951-d8d56771855b",
        "fromTable": "_FCT_DRIVER_SHARE",
        "fromColumn": "VERSION",
        "toTable": "VERSION",
        "toColumn": "VERSION"
      },
      {
        "name": "2ff4c32a-fe6b-4192-9aa0-32128c616287",
        "fromTable": "_FCT_DRIVER_SHARE",
        "fromColumn": "FLIGHT",
        "toTable": "FLIGHT",
        "toColumn": "FLT_DESC"
      },
      {
        "name": "ce7b3592-9283-46ec-a3ff-c9bc5bed4ac8",
        "fromTable": "_FCT_DRIVER_SHARE",
        "fromColumn": "MONTH_ID",
        "toTable": "MONTH",
        "toColumn": "MONTH_ID"
      },
      {
        "name": "6bebf2f2-4eb8-407e-bda1-38e19215899e",
        "fromTable": "_FCT_DRIVER_SHARE",
        "fromColumn": "PNL_ITEM",
        "toTable": "PROFIT_LOSS",
        "toColumn": "ITEM"
      },
      {
        "name": "8a8f55de-94f6-4b97-906e-8423985309cb",
        "fromTable": "CALENDAR",
        "fromColumn": "MONTH_ID",
        "toTable": "MONTH",
        "toColumn": "MONTH_ID",
        "isActive": false
      }
    ],
    "roles": [
      {
        "name": "Admins",
        "modelPermission": "readRefresh",
        "members": [
          {
            "memberName": "WIN-2016_SQL\\Administrator",
            "memberId": "S-1-5-21-911536897-2377122139-487293552-500"
          },
          {
            "memberName": "WIN-2016_SQL\\vzheltun",
            "memberId": "S-1-5-21-911536897-2377122139-487293552-1010"
          },
          {
            "memberName": "WIN-2016_SQL\\cognos",
            "memberId": "S-1-5-21-911536897-2377122139-487293552-1000"
          },
          {
            "memberName": "WIN-2016_SQL\\pdobrokhotov",
            "memberId": "S-1-5-21-911536897-2377122139-487293552-1004"
          }
        ]
      },
      {
        "name": "Users",
        "modelPermission": "read"
      }
    ],
    "expressions": [
      {
        "name": "DIM_PATH",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #\"SQL/ ;DWH_VC_AVT\",",
          "    dbo_V_DIM_PATH = Source{[Schema=\"dbo\",Item=\"V_DIM_PATH\"]}[Data]",
          "in",
          "    dbo_V_DIM_PATH"
        ]
      },
      {
        "name": "DIM_AIRPORT_ORG",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #\"SQL/ ;DWH_VC_AVT\",",
          "    dbo_DIM_AIRPORT = Source{[Schema=\"dbo\",Item=\"DIM_AIRPORT\"]}[Data]",
          "in",
          "    dbo_DIM_AIRPORT"
        ]
      },
      {
        "name": "DIM_FLIGHT",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #\"SQL/ ;DWH_VC_AVT\",",
          "    dbo_DIM_FLIGHT = Source{[Schema=\"dbo\",Item=\"DIM_FLIGHT\"]}[Data]",
          "in",
          "    dbo_DIM_FLIGHT"
        ]
      },
      {
        "name": "DIM_AIRPORT_DST",
        "kind": "m",
        "expression": [
          "let",
          "    Source = #\"SQL/ ;DWH_VC_AVT\",",
          "    dbo_DIM_AIRPORT = Source{[Schema=\"dbo\",Item=\"DIM_AIRPORT\"]}[Data]",
          "in",
          "    dbo_DIM_AIRPORT"
        ]
      },
      {
        "name": "PATH_JOINED",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Table.NestedJoin(DIM_PATH, {\"ORG_AIRPORT\"}, DIM_AIRPORT_ORG, {\"LATITUDE\"}, \"DIM_AIRPORT_ORG\", JoinKind.LeftOuter),",
          "    #\"Expanded DIM_AIRPORT_ORG\" = Table.ExpandTableColumn(Source, \"DIM_AIRPORT_ORG\", {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}, {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded DIM_AIRPORT_ORG\",{{\"COUNTRY_CODE\", \"ORG_COUNTRY_CODE\"}, {\"COUNTRY_DESC\", \"ORG_COUNTRY_NAME\"}, {\"REGION_CODE\", \"ORG_REGION_CODE\"}, {\"ORG_DST\", \"OND\"}, {\"ORG_DST_TYPE\", \"PATH_TYPE\"}, {\"VIA_AIRPORT\", \"PATH_VIA_AIRPORT\"}}),",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Renamed Columns\", {\"DST_AIRPORT\"}, DIM_AIRPORT_DST, {\"AIRPORT_CODE\"}, \"DIM_AIRPORT_DST\", JoinKind.LeftOuter),",
          "    #\"Expanded DIM_AIRPORT_DST\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DIM_AIRPORT_DST\", {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}, {\"COUNTRY_CODE\", \"COUNTRY_DESC\", \"REGION_CODE\"}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded DIM_AIRPORT_DST\",{{\"COUNTRY_CODE\", \"DST_COUNTRY_CODE\"}, {\"COUNTRY_DESC\", \"DST_COUNTRY_NAME\"}, {\"REGION_CODE\", \"DST_REGION_CODE\"}}),",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Renamed Columns1\", {\"PATH_KEY\"}, DIM_FLIGHT, {\"FLT_DESC\"}, \"DIM_FLIGHT\", JoinKind.LeftOuter),",
          "    #\"Expanded DIM_FLIGHT\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"DIM_FLIGHT\", {\"FLT_NUM\", \"HAUL\", \"FLT_TYPE_INT_DOM\", \"FLT_TYPE_SCH_CHR\", \"FLT_TYPE_PSN_CAR\", \"FLT_TYPE_OWH_OAL\", \"COUNTRY_TURNOVER\", \"DEST_GROUP\"}, {\"FLT_NUM\", \"HAUL\", \"FLT_TYPE_INT_DOM\", \"FLT_TYPE_SCH_CHR\", \"FLT_TYPE_PSN_CAR\", \"FLT_TYPE_OWH_OAL\", \"COUNTRY_TURNOVER\", \"DEST_GROUP\"})",
          "in",
          "    #\"Expanded DIM_FLIGHT\""
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}