CREATE TABLE [sim].[HST_DD_SCH] (
    [RECORD_SERIAL_NUMBER]                    INT           NULL,
    [RECORD_TYPE]                             VARCHAR (1)   NULL,
    [AIRLINE_DESIGNATOR]                      VARCHAR (3)   NOT NULL,
    [FLIGHT_NUMBER]                           VARCHAR (5)   NOT NULL,
    [AIRLINE_DESIGNATOR_OP]                   VARCHAR (3)   NOT NULL,
    [FLIGHT_NUMBER_OP]                        VARCHAR (5)   NULL,
    [ITINERARY_VARIATION_IDENTIFIER]          VARCHAR (2)   NULL,
    [LEG_SEQUENCE_NUMBER]                     VARCHAR (2)   NULL,
    [SERVICE_TYPE]                            VARCHAR (1)   NULL,
    [OPERATION_PERIOD_FROM]                   DATE          NULL,
    [OPERATION_PERIOD_TO]                     DATE          NULL,
    [FLIGHT_DATE]                             DATE          NOT NULL,
    [FLIGHT_DOW_NAME]                         VARCHAR (3)   NULL,
    [FLIGHT_DOW_NUM]                          INT           NULL,
    [OPERATION_WEEKDAY_LIST]                  VARCHAR (7)   NULL,
    [FREQUENCY_RATE]                          VARCHAR (1)   NULL,
    [DEPARTURE_STATION]                       VARCHAR (3)   NULL,
    [PASSENGER_STD]                           TIME (7)      NULL,
    [AIRCRAFT_STD]                            TIME (7)      NULL,
    [TIME_VARIATION_DEPARTURE]                VARCHAR (255) NULL,
    [ARRIVAL_STATION]                         VARCHAR (3)   NULL,
    [AIRCRAFT_STA]                            TIME (7)      NULL,
    [PASSENGER_STA]                           TIME (7)      NULL,
    [TIME_VARIATION_ARRIVAL]                  VARCHAR (255) NULL,
    [AIRCRAFT_TYPE]                           VARCHAR (3)   NULL,
    [AIRCRAFT_CONFIGURATION_VERSION]          VARCHAR (20)  NULL,
    [OPERATIONAL_SUFFIX]                      VARCHAR (1)   NULL,
    [PASSENGER_TERMINAL_DEPARTURE]            VARCHAR (2)   NULL,
    [PASSENGER_TERMINAL_ARRIVAL]              VARCHAR (2)   NULL,
    [PRBD]                                    VARCHAR (20)  NULL,
    [PRBM]                                    VARCHAR (5)   NULL,
    [MEAL_SERVICE_NOTE]                       VARCHAR (10)  NULL,
    [JOINT_OPERATIONAL_AIRLINE_DESIGNATOR]    VARCHAR (9)   NULL,
    [LEG_DEPARTURE_STATUS]                    VARCHAR (1)   NULL,
    [INTERNATIONAL_DOMESTIC_STATUS]           VARCHAR (1)   NULL,
    [ITINERARY_VARIATION_IDENTIFIER_OVERFLOW] VARCHAR (1)   NULL,
    [AIRCRAFT_OWNER]                          VARCHAR (3)   NULL,
    [COCKPIT_CREW_EMPLOYER]                   VARCHAR (3)   NULL,
    [CABIN_CREW_EMPLOYER]                     VARCHAR (3)   NULL,
    [AIRLINE_DESIGNATOR_ONWARD]               VARCHAR (3)   NULL,
    [FLIGHT_NUMBER_ONWARD]                    VARCHAR (4)   NULL,
    [AIRCRAFT_ROTATION_LAYOVER_ONWARD]        VARCHAR (1)   NULL,
    [OPERATIONAL_SUFFIX_ONWARD]               VARCHAR (1)   NULL,
    [FLIGHT_TRANSIT_LAYOVER]                  VARCHAR (1)   NULL,
    [CODE_SHARING]                            VARCHAR (1)   NULL,
    [TRAFFIC_RESTRICTION_CODE]                VARCHAR (11)  NULL,
    [LEG_OVERFLOW_INDICATOR]                  VARCHAR (1)   NULL,
    [BILATERAL_INFORMATION]                   VARCHAR (2)   NULL,
    [ACTIVE]                                  BIT           NOT NULL,
    [FILE_NAME]                               VARCHAR (255) NOT NULL,
    [LOAD_DATE]                               SMALLDATETIME NOT NULL,
    CONSTRAINT [PK_STG_SSIM_HST] PRIMARY KEY CLUSTERED ([AIRLINE_DESIGNATOR] ASC, [FLIGHT_NUMBER] ASC, [FLIGHT_DATE] ASC, [FILE_NAME] ASC, [LOAD_DATE] ASC)
);

