



CREATE VIEW [dbo].[V_FCT_SCHEDULE_FLIGHT_PTP] as 

SELECT  DISTINCT 
	 FLT_DESC        = [DEPARTURE_STATION] + '-' + [AIRLINE_DESIGNATOR]    + [FLIGHT_NUMBER]        + '-' + [ARRIVAL_STATION]
	,FLT_DESC_OP     = [DEPARTURE_STATION] + '-' + [AIRLINE_DESIGNATOR_OP] + [FLIGHT_NUMBER_OP]     + '-' + [ARRIVAL_STATION] 
	,FLIGHT_DATE     = CAST ( [DEPARTURE_DATE] AS DATE )
	,DEP_TIME        = [DEPARTURE_DATE]  
	,ARR_TIME        = [ARRIVAL_DATE]
	,[AIRCRAFT_TYPE]
	,VERSION         = 'FCST'
	,DEPARTURES      = 1 
	,DISTANCE        = [dbo].[FS_GET_DISTANCE_BEETWEEN_AIRPORTS]([DEPARTURE_STATION] , [ARRIVAL_STATION] , 'km' ) 
	,BH              = cast( ROUND( DATEDIFF (MI ,[DEPARTURE_DATE] , [ARRIVAL_DATE] ) / 1.0 /60 , 2 ) as float )
	,SEATS           = [CAPACITY_C] +  [CAPACITY_W]+ [CAPACITY_S] 
	,SEATS_C         = [CAPACITY_C]
	,SEATS_W         = [CAPACITY_W]
	,SEATS_S         = [CAPACITY_S]
FROM [sim].[DAT_DD_SCH_CAP]




